- name: Enter admin password
  pause:
    prompt: "Enter password for nagiosadmin user"
    echo: no
  register: nagios_admin_password

- name: Update System and Install required packages
  import_tasks: update-install.yml

- name: Setup users and groups
  import_tasks: user-group.yml

- name: Download, Compile and Install Nagios
  import_tasks: install-nagios.yml

- name: Download, Compile and Install Nagios Plugins
  import_tasks: install-plugins.yml

- name: Setup SELinux and firewall
  import_tasks: allow-firewall.yml

- name: Setup Remote Clients
  import_tasks: setup-clients.yml
