---
- name: Update system packages
  become: yes
  package:
   name: "*"
   state: latest

- name: Prepare directories and binaries
  include: pre-setup.yml

- name: Configure the Kubernetes API Server
  include: api-server.yml

- name: Configure the Kubernetes Controller Manager
  include: control-manager.yml

- name: Configure the Kubernetes Scheduler
  include: scheduler.yml

- name: Start the Services
  include: start-services.yml

- name: Enable HTTP Health Checks
  include: health-checks.yml

- name: RBAC for Kubelet Authorization
  include: rbac-auth.yml
