- name: Create argocd namespace
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: argocd
    state: present

- name: Deploy ArgoCD
  shell: |
    kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

- name: Patch Service to expose on NodePort
  shell: |
    kubectl patch svc argocd-server -n argocd --patch \
    '{"spec": { "type": "NodePort", "ports": [ { "nodePort": 31000, "port": 443, "protocol": "TCP", "targetPort": 8080 } ] } }'

- name: Get initial password
  shell: |
    kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d
  register: argo_init_pass
  tags:
    - do

- name: ArgoCD initial admin password
  debug:
    msg: "{{ argo_init_pass.stdout }}"
  tags:
    - do
