- name: Download Nagios Plugins
  shell: |
    wget https://nagios-plugins.org/download/nagios-plugins-2.2.1.tar.gz
    tar -zxvf nagios-plugins-2.2.1.tar.gz
  args:
    chdir: /tmp

- name: Compile and Install Nagios Plugins
  shell: |
    ./configure --with-nagios-user=nagios --with-nagios-group=nagios
    make
    make install
  args:
    chdir: /tmp/nagios-plugins-2.2.1/

- name: Verify Nagios configuration files
  shell: |
    /usr/local/nagios/bin/nagios -v /usr/local/nagios/etc/nagios.cfg

- name: Restart and Enable Nagios
  service:
    name: nagios
    state: started
    enabled: yes
