---
###
### Run on localhost from which you control the machines in GCP.
### Must have installed and configured the gcloud cli, kubectl and cfssl
###

- name: Generate Certifications and Configs
  hosts: localhost

  vars:
    k8s_hostnames: "kubernetes,kubernetes.default,kubernetes.default.svc,kubernetes.default.svc.cluster,kubernetes.svc.cluster.local"
    service_cluster_ip_range: "10.32.0.1"
    controller_ips: "10.240.0.10,10.240.0.11"

  roles:
    - gen-cert-conf
