- name: Update system packages
  package:
   name: "*"
   state: latest

- name: Install requirements
  package:
   name: "{{ item }}"
  loop:
   - ca-certificates
   - curl
   - gnupg
   - lsb-release

- name: Download Docker packages
  shell: |
    curl -o docker-ce.deb \
      https://download.docker.com/linux/ubuntu/dists/focal/pool/stable/amd64/docker-ce_20.10.9~3-0~ubuntu-focal_amd64.deb
    curl -o docker-cli.deb \
      https://download.docker.com/linux/ubuntu/dists/focal/pool/stable/amd64/docker-ce-cli_20.10.9~3-0~ubuntu-focal_amd64.deb
    curl -o containerd.deb \
      https://download.docker.com/linux/ubuntu/dists/focal/pool/stable/amd64/containerd.io_1.6.6-1_amd64.deb
    curl -o docker-compose-plugin.deb \
      https://download.docker.com/linux/ubuntu/dists/focal/pool/stable/amd64/docker-compose-plugin_2.6.0~ubuntu-focal_amd64.deb

- name: Install Docker
  shell: |
    dpkg -i --force-all containerd.deb
    dpkg -i --force-all docker-cli.deb
    dpkg -i --force-all docker-ce.deb
    dpkg -i --force-all docker-compose-plugin.deb
  tags:
    - dodo
