- name: Update system packages
  package:
   name: "*"
   state: latest

- name: Install requirements
  package:
   name: "{{ item }}"
  loop:
   - ca-certificates
   - curl
   - gnupg
   - lsb-release

- name: Create gpg dir
  file:
    path: /etc/apt/keyrings
    state: directory

- name: Add gpg
  shell: |
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg

- name: Setup repo
  shell: |
    echo \
     "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
     $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: Update apt cache
  apt:
   update_cache: yes

- name: Install docker
  package:
    name: "{{ item }}"
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose-plugin
