- name: Deploy CoreDNS
  import_tasks: coredns.yml

- name: Generate /etc/hosts files
  import_tasks: configure_hosts.yml

# Install Docker for "docker run" in containers used by Jenkins
- name: Install Docker Engine
  import_tasks: install-docker.yml
  tags:
    - docker

# Create directories for Persistent Volumes used by Jenkins, Prometheus, Grafana
- name: Create directories for PVs
  import_tasks: create-pv-dir.yml
  when: inventory_hostname in groups['workers']
  tags:
    - pvdir
